using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;

namespace DevOSRing.Core.Llm.Canned;

/// <summary>
/// LLM-less review generator. Inspects a unified diff and surfaces:
/// changed file list, line counts, and a heuristic risk scan (TODOs, console.log,
/// hardcoded secrets, large blast radius). Output is Markdown for the companion webview.
/// </summary>
public static class CannedReview
{
    private static readonly (string Pattern, string Label)[] RiskPatterns = new[]
    {
        (@"\bTODO\b|\bFIXME\b|\bHACK\b", "TODO/FIXME/HACK comment introduced"),
        (@"console\.log\s*\(",            "console.log left in"),
        (@"\bConsole\.WriteLine\s*\(",    "Console.WriteLine left in"),
        (@"\bprint\s*\(",                 "print() left in (debug)"),
        (@"(?i)(api[_-]?key|secret|token|password)\s*[:=]\s*[""'][^""']{6,}", "possible hardcoded secret"),
        (@"\.only\s*\(|\.skip\s*\(",      "test focus / skip left in"),
        (@"DROP\s+TABLE|TRUNCATE\s+TABLE", "destructive SQL"),
    };

    public static string Summarise(string diff)
    {
        if (string.IsNullOrWhiteSpace(diff))
            return "## Working tree clean\n\nThere is nothing to review.\n";

        var lines = diff.Replace("\r\n", "\n").Split('\n');

        var files = new List<string>();
        int added = 0, removed = 0;
        foreach (var ln in lines)
        {
            if (ln.StartsWith("+++ b/")) files.Add(ln.Substring(6));
            else if (ln.StartsWith("+") && !ln.StartsWith("+++")) added++;
            else if (ln.StartsWith("-") && !ln.StartsWith("---")) removed++;
        }

        var risks = ScanRisks(lines);
        var heroFile = files.OrderBy(f => f).FirstOrDefault();

        var sb = new StringBuilder();
        sb.AppendLine("## Summary");
        sb.AppendLine();
        sb.AppendLine($"Touched **{files.Count} file{(files.Count == 1 ? "" : "s")}** " +
                      $"(`+{added}` / `-{removed}` lines). " +
                      (heroFile != null ? $"Main change appears to be in `{heroFile}`." : ""));
        sb.AppendLine();

        sb.AppendLine("## Files changed");
        sb.AppendLine();
        foreach (var f in files.OrderBy(f => f))
        {
            sb.AppendLine($"- `{f}`");
        }
        if (files.Count == 0) sb.AppendLine("- _(no files parsed)_");
        sb.AppendLine();

        sb.AppendLine("## Risks");
        sb.AppendLine();
        if (risks.Count == 0)
        {
            sb.AppendLine("- None spotted by heuristics.");
        }
        else
        {
            foreach (var r in risks.Distinct())
            {
                sb.AppendLine($"- {r}");
            }
        }
        sb.AppendLine();

        sb.AppendLine("## Suggestions");
        sb.AppendLine();
        if (added + removed > 400)
            sb.AppendLine("- Diff is large (>400 lines changed). Consider splitting into focused commits.");
        if (files.Count > 10)
            sb.AppendLine("- Broad blast radius (>10 files). Add a short \"why\" to the commit body.");
        if (risks.Count == 0 && added + removed <= 400 && files.Count <= 10)
            sb.AppendLine("- Looks good. Consider adding tests covering the new behaviour.");
        sb.AppendLine();

        sb.AppendLine("---");
        sb.AppendLine("_Generated by DevOS canned review (configure an LLM API key in plugin settings for a real review)._");

        return sb.ToString();
    }

    private static List<string> ScanRisks(string[] lines)
    {
        var result = new List<string>();
        foreach (var line in lines)
        {
            if (!line.StartsWith("+") || line.StartsWith("+++")) continue;
            var added = line.Substring(1);
            foreach (var (pattern, label) in RiskPatterns)
            {
                if (Regex.IsMatch(added, pattern))
                {
                    result.Add(label);
                }
            }
        }
        return result;
    }
}
